#!/bin/bash
# Setup script for Juno Analytics Terraform Infrastructure
# This script creates the necessary GCS buckets for storing Terraform state

set -e

echo "========================================="
echo "Juno Analytics Terraform Setup"
echo "========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored messages
print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Check if gcloud is installed
if ! command -v gcloud &> /dev/null; then
    print_error "gcloud CLI is not installed. Please install it first:"
    echo "  https://cloud.google.com/sdk/docs/install"
    exit 1
fi

print_success "gcloud CLI found"

# Check if user is authenticated
if ! gcloud auth list --filter=status:ACTIVE --format="value(account)" &> /dev/null; then
    print_warning "Not authenticated with gcloud"
    print_info "Running authentication..."
    gcloud auth application-default login
fi

print_success "Authenticated with gcloud"

# Get current project
CURRENT_PROJECT=$(gcloud config get-value project 2>/dev/null)
print_info "Current project: ${CURRENT_PROJECT}"

echo ""
echo "========================================="
echo "Environment Selection"
echo "========================================="
echo ""
echo "Which environment do you want to set up?"
echo "1) DEV (junoplus-dev)"
echo "2) PROD (juno-9dfb6)"
echo "3) Both"
read -p "Enter choice [1-3]: " ENV_CHOICE

create_state_bucket() {
    local PROJECT_ID=$1
    local ENVIRONMENT=$2
    local BUCKET_NAME="${PROJECT_ID}-terraform-state"
    local REGION="us-central1"
    
    print_info "Setting up Terraform state bucket for ${ENVIRONMENT}..."
    
    # Check if bucket already exists
    if gsutil ls -p ${PROJECT_ID} gs://${BUCKET_NAME} &> /dev/null; then
        print_warning "Bucket gs://${BUCKET_NAME} already exists. Skipping creation."
    else
        print_info "Creating bucket: gs://${BUCKET_NAME}..."
        gsutil mb -p ${PROJECT_ID} -l ${REGION} gs://${BUCKET_NAME}/
        print_success "Bucket created"
    fi
    
    # Enable versioning
    print_info "Enabling versioning on bucket..."
    gsutil versioning set on gs://${BUCKET_NAME}/
    print_success "Versioning enabled"
    
    # Set lifecycle policy (optional - keeps last 5 versions)
    print_info "Setting lifecycle policy..."
    cat > /tmp/lifecycle.json <<EOF
{
  "lifecycle": {
    "rule": [
      {
        "action": {"type": "Delete"},
        "condition": {
          "numNewerVersions": 5
        }
      }
    ]
  }
}
EOF
    gsutil lifecycle set /tmp/lifecycle.json gs://${BUCKET_NAME}/
    rm /tmp/lifecycle.json
    print_success "Lifecycle policy set"
    
    # Update backend config file
    local BACKEND_FILE="environments/backend-${ENVIRONMENT}.tfvars"
    print_info "Updating ${BACKEND_FILE}..."
    cat > ${BACKEND_FILE} <<EOF
# Backend configuration for ${ENVIRONMENT^^} environment
# Auto-generated by setup.sh

bucket = "${BUCKET_NAME}"
prefix = "terraform/state/${ENVIRONMENT}"
EOF
    print_success "${BACKEND_FILE} updated"
    
    echo ""
}

# Create buckets based on user choice
case $ENV_CHOICE in
    1)
        create_state_bucket "junoplus-dev" "dev"
        ;;
    2)
        create_state_bucket "juno-9dfb6" "prod"
        ;;
    3)
        create_state_bucket "junoplus-dev" "dev"
        create_state_bucket "juno-9dfb6" "prod"
        ;;
    *)
        print_error "Invalid choice"
        exit 1
        ;;
esac

echo ""
echo "========================================="
echo "Configuration Files Setup"
echo "========================================="
echo ""

# Create .tfvars files from examples if they don't exist
if [ ! -f "environments/dev.tfvars" ]; then
    print_info "Creating environments/dev.tfvars from example..."
    cp environments/dev.tfvars.example environments/dev.tfvars
    print_success "Created environments/dev.tfvars"
else
    print_warning "environments/dev.tfvars already exists. Skipping."
fi

if [ ! -f "environments/prod.tfvars" ]; then
    print_info "Creating environments/prod.tfvars from example..."
    cp environments/prod.tfvars.example environments/prod.tfvars
    print_success "Created environments/prod.tfvars"
else
    print_warning "environments/prod.tfvars already exists. Skipping."
fi

echo ""
echo "========================================="
echo "✅ Setup Complete!"
echo "========================================="
echo ""
print_success "Terraform state buckets are ready"
print_success "Configuration files created"
echo ""
print_info "Next steps:"
echo ""
echo "1. Review and edit configuration files:"
echo "   - environments/dev.tfvars"
echo "   - environments/prod.tfvars"
echo ""
echo "2. Initialize Terraform for DEV:"
echo "   ${BLUE}make init-dev${NC}"
echo ""
echo "3. Plan your deployment:"
echo "   ${BLUE}make plan-dev${NC}"
echo ""
echo "4. Apply changes:"
echo "   ${BLUE}make apply-dev${NC}"
echo ""
echo "Or use the Makefile for easier commands: ${BLUE}make help${NC}"
echo ""
